### ISSUE TITLE
Pimatic <get variable> node overwrites the complete msg payload

### ISSUE THREAD

**Issue by emeins** [mwittig/node-red-contrib-pimatic#5]
It seems that the Pimatic <get variable> node overwrites the full input msg payload. So values from earlier operations need to be stored in other variables to be available for later steps. Would it be possible to preserve the data or implement an option like it is done in the dashboard switch node:
![image](https://user-images.githubusercontent.com/17033201/51985552-6a65cd00-249e-11e9-9e81-ee580a10640a.png)

**Comment by mwittig** [comment]
Released node-red-contrib-pimatic@1.2.0
